### ISSUE TITLE
Heading and text styles per Style Guide

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-citylimits#105]
Link to Style Guide: https://drive.google.com/open?id=1sD3tQcKdQckrxq6TXN6kQ8SqzVy4x-DW

- [ ] H1: Roc Grotesk Bold, 64px, black
- [ ] H2: (PRIMARY) Roc Grotesk Bold, 40px, black
- [ ] H2: (SECTION HEADING) Roc Grotesk Bold, 18px, text-transform: uppercase, black
- [ ] H3: Roc Grotesk Bold, 26px, black
- [ ] H4: Roc Grotesk Bold, 18px, black
- [ ] p: Neue Haas Grotesk Text Pro Regular, 18px, #6E6A69
- [ ] Excerpts: Neue Haas Grotesk Text Pro Regular, 16px, #6E6A69
- [ ] Pull Quote: Roc Grotesk ExtraBold, 32px, black (the quotation marks are #E62322)
- [ ] Drop caps: Neue Haas Grotesk Text Pro 75 Bold, 64px, black

**Comment by benlk** [comment]
@kaylima The mockups use smaller fonts for headlines on mobile; is there any guidance for that?

Note that `h3.widgettitle` should use the "h2 section heading" styles, and that what's in most widgets as an `h4` or `h5` should use the "h3" styles.

**Comment by kaylima** [comment]
Mobile styles:

 H1: Roc Grotesk Bold, 28px, black
 H2: (PRIMARY) Roc Grotesk Bold, 18px, black
 H2: (SECTION HEADING) Roc Grotesk Bold, 18px, text-transform: uppercase, black
Categories: Roc Grotesk Medium, 13px, #E62322
 p: Neue Haas Grotesk Text Pro Regular, 18px, #6E6A69
 Excerpts: N/A
 Pull Quote: Roc Grotesk ExtraBold, 24px, black (the quotation marks are #E62322)
 Drop caps: Neue Haas Grotesk Text Pro 75 Bold, 64px, black

I don't have mobile info for but can get it if needed:
 H3: Roc Grotesk Bold, 26px, black
 H4: Roc Grotesk Bold, 18px, black

This all taken directly from the Working Files (v13): https://drive.google.com/open?id=1_MRgrWOK07dVH487kmRtGEJhfeW5jlps

The working files should be used as a reference throughout the front-end build-out. Let me now if you have any questions about that.

**Comment by benlk** [comment]
- [x] Roc Grotesk Bold
- [x] Roc Grotesk ExtraBold
- [x] Neue Haas Grotesk Text Pro Regular
- [x] Neue Haas Grotesk Text Pro Bold

- [x] body text color is #6E6A69, not `black`
- [ ] s/beige/tan/ across site UI
- [ ] replace greys on white backgrounds with `@grey1`
- [ ] replace font-sans with font-body
- [ ] remove font-serif

**Comment by benlk** [comment]
I've been working off of the October 1 flats; I didn't know until today that there was an October 2 Working File. The flats are advantageous because they don't require me to have the fonts installed on my computer via a paid Adobe Creative Cloud subscription.
